apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test-web-app-serverless
  namespace: webapp
spec:
  template:
    spec:
      containers:
        - image: hsmto25519/web-app:v1.0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30